# This file will hold the code to generate the crafting list and spit out the combined results. 

# Still kinda wanna sort the results if I can... (4-21-2023)
# completed all lev 1-20 

# import os


# Raw gathered materials master list

copper_ore = "Copper Ore"
fire_shard = "Fire Shard"
ice_shard = "Ice Shard"
wind_shard = "Wind Shard"
earth_shard = "Earth Shard"
lightning_shard = "Lightning Shard"
water_shard = "Water Shard"
muddy_water = "Muddy Water"
bone_chip = "Bone Chip"
latex = "Latex"
allagan_snail = "Allagan Snail"
maple_sap = "Maple Sap"
maple_log = "Maple Log"
cinnamon = "Cinnamon"
maple_branch = "Maple Branch"
beehive_chip = "Beehive Chip"
firelight_seeds = "Firelight Seeds"
icelight_seeds = "Icelight Seeds"
windlight_seeds = "Windlight Seeds"
earthlight_seeds = "Earthlight Seeds"
levinlight_seeds = "Levinlight Seeds"
waterlight_seeds = "Waterlight Seeds"
tin_ore = "Tin Ore"
raw_sunstone = "Raw Sunstone"
raw_lapis_lazuli = "Raw Lapis Lazuli"
soiled_femur = "Soiled Femur"
zinc_ore = "Zinc Ore"
obsidian = "Obsidian"
potters_clay = "Potter's Clay"
cock_feather = "Cock Feather"
tinolqa_mistletoe = "Tinolqa Mistletoe"
la_noscean_orange = "La Noscean Orange"
la_noscean_orange_seeds = "La Noscean Orange Seeds"
ash_log = "Ash Log"
kukuru_bean = "Kukuru Bean"
ash_branch = "Ash Branch"
cloves = "Cloves"
crow_feather = "Crow Feather"
iron_ore = "Iron Ore"
fine_sand = "Fine Sand"
copper_sand = "Copper Sand"
rock_salt = "Rock Salt"
ragstone = "Ragstone"
iron_sand = "Iron Sand"
cinnabar = "Cinnabar"
elm_log = "Elm Log"
gridanian_chestnut = "Gridanian Chestnut"
lowland_grapes = "Lowland Grapes"
chanterelle = "Chanterelle"
rye = "Rye"
sunset_wheat = "Sunset Wheat"
garlean_garlic = "Garlean Garlic"
tree_toad = "Tree Toad"
moko_grass = "Moko Grass"
yellow_ginseng = "Yellow Ginseng"
lowland_grape_seeds = "Lowland Grape Seeds"
garlic_cloves = "Garlic Cloves"
wild_onion = "Wild Onion"
buffalo_beans = "Buffalo Beans"
straw = "Straw"
lavender = "Lavender"
grass_viper = "Grass Viper"
wild_onion_set = "Wild Onion Set"
lavender_seeds = "Lavender Seeds"
coerthan_carrot = "Coerthan Carrot"
ogre_pumpkin = "Ogre Pumpkin"
la_noscean_lettuce = "La Noscean Lettuce"
cinderfoot_olive = "Cinderfoot Olive"
humus = "Humus"
carnation = "Carnation"
coerthan_carrot_seeds = "Coerthan Carrot Seeds"
la_noscean_lettuce_seeds = "La Noscean Lettuce Seeds"
olive_seeds = "Olive Seeds"
cieldalaes_spinach = "Cieldalaes Spinach"
black_pepper = "Black Pepper"
cotton_boll = "Cotton Boll"
black_pepper_seeds = "Black Pepper Seeds"
ruby_tomato = "Ruby Tomato"
alpine_parsnip = "Alpine Parsnip"
highland_parsley = "Highland Parsley"
marjoram = "Marjoram"
raw_malachite = "Raw Malachite"
raw_sphene = "Raw Sphene"
raw_fluorite = "Raw Fluorite"
raw_danburite = "Raw Danburite"
sunrise_tellin = "Sunrise Tellin"
alumen = "Alumen"
limestone = "Limestone"
mudstone = "Mudstone"
grade_1_carbonized_matter = "Grade 1 Carbonized Matter"
faerie_apple = "Faerie Apple"
faerie_apple_seeds = "Faerie Apple Seeds"
sun_lemon = "Sun Lemon"
sun_lemon_seeds = "Sun Lemon Seeds"
nopales = "Nopales"
yew_log = "Yew Log"
yew_branch = "Yew Branch"
paprika = "Paprika"
galago_mint = "Galago Mint"
paprika_seeds = "Paprika Seeds"
lalafellin_lentil = "Lalafellin Lentil"
popoto = "Popoto"
belladonna = "Belladonna"
popoto_set = "Popoto Set"
gil_bun = "Gil Bun"
island_seedling = "Island Seedling"
shroud_seedling = "Shroud Seedling"
desert_seedling = "Desert Seedling"
white_scorpion = "White Scorpion"
effervescent_water = "Effervescent Water"
silver_ore = "Silver Ore"
earth_rock = "Earth Rock"
silver_sand = "Silver Sand"
fire_rock = "Fire Rock"
ice_rock = "Ice Rock"
wind_rock = "Wind Rock"
lightning_rock = "Lightning Rock"
water_rock = "Water Rock"
gridanian_walnut = "Gridanian Walnut"
matrons_mistletoe = "Matron's Mistletoe"
walnut_log = "Walnut Log"
pixie_plums = "Pixie Plums"
pixie_plum_seeds = "Pixie Plum Seeds"
noble_grapes = "Noble Grapes"
button_mushroom = "Button Mushroom"
ala_mhigan_mustard = "Ala Mhigan Mustard"
pearl_ginger = "Pearl Ginger"
chamomile = "Chamomile"
pearl_ginger_root = "Pearl Ginger Root"
chamomile_seeds = "Chamomile Seeds"
sticky_rice = "Sticky Rice"
millioncorn = "Millioncorn"
millioncorn_seeds = "Millioncorn Seeds"
fire_crystal = "Fire Crystal"
ice_crystal = "Ice Crystal"
wind_crystal = "Wind Crystal"
earth_crystal = "Earth Crystal"
lightning_crystal = "Lightning Crystal"
water_crystal = "Water Crystal"
wyvern_obsidian = "Wyvern Obsidian"
saltpeter = "Saltpeter"
bomb_ash = "Bomb Ash"
silex = "Silex"
blue_pigment = "Blue Pigment"
red_pigment = "Red Pigment"
yellow_pigment = "Yellow Pigment"
grey_pigment = "Grey Pigment"
brown_pigment = "Brown Pigment"
green_pigment = "Green Pigment"
purple_pigment = "Purple Pigment"
brimstone = "Brimstone"
siltstone = "Siltstone"
grade_1_la_noscean_topsoil = "Grade 1 La Noscean Topsoil"
grade_1_shroud_topsoil = "Grade 1 Shroud Topsoil"
grade_1_thanalan_topsoil = "Grade 1 Thanalan Topsoil"
chocobo_feather = "Chocobo Feather"
alligator_pear = "Alligator Pear"
jade_peas = "Jade Peas"
wizard_eggplant = "Wizard Eggplant"
wizard_eggplant_seeds = "Wizard Eggplant Seeds"
midland_cabbage = "Midland Cabbage"
midland_cabbage_seeds = "Midland Cabbage Seeds"
moor_leech = "Moor Leech"
granite = "Granite"
raw_garnet = "Raw Garnet"
little_worm = "Little Worm"
raw_heliodor = "Raw Heliodor"
raw_goshenite = "Raw Goshenite"
raw_peridot = "Raw Peridot"
mythril_ore = "Mythril Ore"
raw_amethyst = "Raw Amethyst"
raw_aquamarine = "Raw Aquamarine"
mythril_sand = "Mythril Sand"
oak_branch = "Oak Branch"
oak_log = "Oak Log"
tarantula = "Trantula"
flax = "Flax"
yafaemi_wildgrass = "Yafaemi Wildgrass"
linseed = "Linseed"
aloe = "Aloe"
midland_basil = "Midland Basil"
midland_basil_seeds = "Midland Basil Seeds"
white_truffle = "White Truffle"
bloodgrass = "Bloodgrass"
mandrake = "Mandrake"
mandrake_seeds = "Mandrake Seeds"
salt_leek = "Salt Leek"
laurel = "Laurel"
wildfowl_feather = "Wildfowl Feather"
dragon_pepper = "Dragon Pepper"
desert_saffron = "Desert Saffron"
raw_tourmaline = "Raw Tourmaline"
raw_spinel = "Raw Spinel"
raw_zircon = "Raw Zircon"
jade = "Jade"
black_alumen = "Black Alumen"
grenade_ash = "Grenade Ash"
iron_acorn = "Iron Acorn"
mahogany_log = "Mahogany Log"
nutmeg = "Nutmeg"
almonds = "Almonds"
almond_seeds = "Almond Seeds"
blood_currants = "Blood Currants"
blood_currant_seeds = "Blood Currant Seeds"
mugwort = "Mugwort"
maiden_artichoke = "Maiden Artichoke"
ramhorn_zucchini = "Ramhorn Zucchini"
thyme = "Thyme"
raw_turquoise = "Raw Turquoise"
electrum_ore = "Electrum Ore"
raw_amber = "Raw Amber"
raw_rubellite = "Raw Rubellite"
electrum_sand = "Electrum Sand"
mirror_apple = "Mirror Apple"
mirror_apple_seeds = "Mirror Apple Seeds"
mistletoe = "Mistletoe"
sagolii_sage = "Sagolii Sage"
black_scorpion = "Black Scorpion"
rolanberry = "Rolanberry"
rolanberry_seeds = "Rolanberry Seeds"
dart_frog = "Dart Frog"
basilisk_egg = "Basilisk Egg"
cobalt_ore = "Cobalt Ore"
adamantoise_shell = "Adamantoise Shell"
ogre_horn = "Ogre Horn"
ice_cluster = "Ice Cluster"
lightning_cluster = "Lightning Cluster"
water_cluster = "Water Cluster"
gold_ore = "Gold Ore"
darksteel_ore = "Darksteel Ore"
coblyn_larva = "Coblyn Larva"
unaspected_crystal = "Unaspected Crystal"
gregarious_worm = "Gregarious Worm"
ferberite = "Ferberite"
native_gold = "Native Gold"
raw_ruby = "Raw Ruby"
raw_diamond = "Raw Diamond"
raw_emerald = "Raw Emerald"
raw_topaz = "Raw Topaz"
raw_iolite = "Raw Iolite"
raw_sapphire = "Raw Sapphire"
dark_matter_cluster = "Dark Matter Cluster"
yellow_copper_ore = "Yellow Copper Ore"
platinum_ore = "Platinum Ore"
dragon_obsidian = "Dragon Obsidian"
virgin_basilisk_egg = "Virgin Basilisk Egg"
grade_2_la_noscean_topsoil = "Grade 2 La Noscean Topsoil"
grade_2_shroud_topsoil = "Grade 2 Shroud Topsoil"
grade_2_thanalan_topsoil = "Grade 2 Thanalan Topsoil"
black_limestone = "Black Limestone"
fire_cluster = "Fire Cluster"
wind_cluster = "Wind Cluster"
earth_cluster = "Earth Cluster"
astral_rock = "Astral Rock"
gold_sand = "Gold Sand"
volcanic_rock_salt = "Volcanic Rock Salt"
umbral_rock = "Umbral Rock"
grade_3_la_noscean_topsoil = "Grade 3 La Noscean Topsoil"
grade_3_shroud_topsoil = "Grade 3 Shroud Topsoil"
grade_3_thanalan_topsoil = "Grade 3 Thanalan Topsoil"
antumbral_rock = "Antumbral Rock"
pumice = "Pumice"
rosewood_log = "Rosewood Log"
rosewood_branch = "Rosewood Branch"
prickly_pineapple = "Prickly Pineapple"
spruce_log = "Spruce Log"
thavnairian_mistletoe = "Thavnairian Mistletoe"
vampire_plant = "Vampire Plant"
prickly_pineapple_seeds = "Prickly Pineapple Seeds"
fragrant_log = "Fragrant Log"
apricot = "Apricot"
blood_orange = "Blood Orange"
bamboo_stick = "Bamboo Stick"
redolent_log = "Redolent Log"
scarlet_sap = "Scarlet Sap"
cypress_log = "Cypress Log"
cedar_log = "Cedar Log"
ebony_log = "Ebony Log"
cedar_branch = "Cedar Branch"
thanalan_tea_leaves = "Thanalan Tea Leaves"
lava_toad = "Lava Toad"
maiden_grass = "Maiden Grass"
dzemael_tomato = "Dzemael Tomato"
honey_lemon = "Honey Lemon"
black_truffle = "Black Truffle"
silkworm_cocoon = "Silkworm Cocoon"
trillium = "Trillium"
trillium_bulb = "Trillium Bulb"
kidragora = "Kidragora"
dzemael_tomato_seeds = "Dzemael Tomato Seeds"
honey_lemon_seeds = "Honey Lemon Seeds"
mazlaya_greens = "Mazlaya Greens"
la_noscean_leek = "La Noscean Leek"
young_cieldalaes_spinach = "Young Cieldalaes Spinach"
waterfowl_feather = "Waterfowl Feather"
shroud_tea_leaves = "Shroud Tea Leaves"
old_world_fig = "Old World Fig"
old_world_fig_Seeds = "Old World Fig Seeds"
rosemary = "Rosemary"
mineral_water = "Mineral Water"
shriekshroom = "Shriekshroom"


# Raw hunted materials master list

animal_sinew = "Animal Sinew"
marbled_eye = "Marbled Eye"
animal_skin = "Animal Skin"
beastkin_blood = "Beastkin Blood"
aldgoat_milk = "Aldgoat Milk"
buffalo_milk = "Buffalo Milk"
marmot_meat = "Marmot Meat"
lominsan_anchovy = "Lominsan Anchovy"
crayfish = "Crayfish"
haddock = "Haddock"
princess_trout = "Princess Trout"
ram_horn = "Ram Horn"
animal_hide = "Animal Hide"
beast_sinew = "Beast Sinew"
coral_butterfly = "Coral Butterfly"
pipira = "Pipira"
bat_fang = "Bat Fang"
viscous_secretions = "Viscous Secretions"
jellyfish_umbrella = "Jellyfish Umbrella"
imp_wing = "Imp Wing"
bat_wing = "Bat Wing"
brass_loach = "Brass Loach"
crimson_crayfish = "Crimson Crayfish"
mutton_loin = "Mutton Loin"
dusk_goby = "Dusk Goby"
dodo_tenderloin = "Dodo Tenderloin"
mole_meat = "Mole Meat"
tiger_cod = "Tiger Cod"
maiden_carp = "Maiden Carp"
antelope_horn = "Antelope Horn"
white_coral = "White Coral"
aldgoat_skin = "Aldgoat Skin"
dodo_feather = "Dodo Feather"
red_landtrap_leaf = "Red Landtrap Leaf"
goobbue_fang = "Goobbue Fang"
yellow_yarzon_leg = "Yellow Yarzon Leg"
dodo_egg = "Dodo Egg"
rothlyt_oyster = "Rothlyt Oyster"
helmet_crab = "Helmet Crab"
chicken_breast = "Chicken Breast"
antelope_shank = "Antelope Shank"
warmwater_trout = "Warmwater Trout"


# Raw bought materials master list

chicken_egg = "Chicken Egg"
sour_red = "Sour Red"
blue_cheese = "Blue Cheese"


# CRAFTING tier 1

maple_lumber = [maple_log, maple_log, maple_log]
bronze_ingot = [copper_ore, copper_ore, tin_ore]
copper_ingot = [copper_ore, copper_ore, copper_ore]
leather = [animal_skin]
hempen_yarn = [moko_grass, moko_grass]
distilled_water = [muddy_water]
quicksilver = [cinnabar, cinnabar]
table_salt = [rock_salt]
maple_syrup = [maple_sap]
bone_hora = [bone_chip, bone_chip, animal_sinew]
animal_glue = [animal_skin, bone_chip, bone_chip]
bone_brand = [marbled_eye, bone_chip]
raisins = [lowland_grapes]
boiled_egg = [chicken_egg, mineral_water]
enchanted_copper_ink = [copper_sand, copper_sand, beastkin_blood]
rye_flour = [rye, rye, rye]
honey = [beehive_chip, beehive_chip, beehive_chip]
bone_staff = [marbled_eye, soiled_femur, bone_chip]
antidote = [rock_salt, grass_viper]
fish_meal = [lominsan_anchovy, lominsan_anchovy, lominsan_anchovy]
marmot_steak = [marmot_meat, wild_onion, garlean_garlic]
rubber = [latex]
ash_lumber = [ash_log, ash_log, ash_log]
ragstone_whetstone = [ragstone, ragstone]
ramhorn_staff = [marbled_eye, ram_horn, ram_horn]
ramhorn_claws = [ram_horn, ram_horn, animal_sinew]
bone_armillae = [soiled_femur, soiled_femur, soiled_femur]
hard_leather = [animal_hide]
eye_drops = [rock_salt, yellow_ginseng]
fish_oil = [princess_trout, princess_trout]
fish_glue = [coral_butterfly, coral_butterfly]
beeswax = [beehive_chip, beehive_chip, beehive_chip]
sweet_cream = [buffalo_milk]
orange_juice = [la_noscean_orange, la_noscean_orange, la_noscean_orange]
sunset_wheat_flour = [sunset_wheat, sunset_wheat, sunset_wheat, sunset_wheat]
smooth_butter = [buffalo_milk, buffalo_milk]
kukuru_butter = [kukuru_bean, kukuru_bean]
mint_lassi = [galago_mint, aldgoat_milk]
ash_radical = [ash_branch, bone_chip, beastkin_blood]
iron_ingot = [iron_ore, iron_ore, iron_ore]
amateurs_needle = [bat_fang]
sunstone = [raw_sunstone]
danburite = [raw_danburite]
fluorite = [raw_fluorite]
sphene = [raw_sphene]
malachite = [raw_malachite]
lapis_lazuli = [raw_lapis_lazuli]
brass_ingot = [copper_ore, copper_ore, zinc_ore]
straw_hat = [straw, straw, straw]
cotton_yarn = [cotton_boll, cotton_boll]
stablemaids_hat = [straw, straw, straw, carnation]
roof_tile = [potters_clay, potters_clay, straw]
clove_oil = [cloves, cloves]
enchanted_iron_ink = [iron_sand, iron_sand, viscous_secretions]
olive_oil = [cinderfoot_olive, cinderfoot_olive, cinderfoot_olive, cinderfoot_olive]
kukuru_powder = [kukuru_bean, kukuru_bean]
tomato_sauce = [ruby_tomato, wild_onion, garlean_garlic]
gelatin = [bat_wing, brass_loach]
elm_lumber = [elm_log, elm_log, elm_log]
blank_grade_1_orchestration_roll = [moko_grass, elm_log]
staghorn_staff = [marbled_eye, antelope_horn, antelope_horn]
coral_armillae = [white_coral, white_coral, white_coral]
mudstone_whetstone = [mudstone, mudstone]
aldgoat_leather = [aldgoat_skin, alumen]
potion_of_intelligence = [rock_salt, beastkin_blood, red_landtrap_leaf]
potion_of_dexterity = [rock_salt, bat_fang]
firebricks = [mudstone, mudstone, potters_clay]
potion_of_vitality = [rock_salt, goobbue_fang, lavender]
jellyfish_humours = [jellyfish_umbrella, jellyfish_umbrella]
potion_of_strength = [rock_salt, yellow_yarzon_leg, white_scorpion]
potion_of_mind = [rock_salt, viscous_secretions, jellyfish_umbrella]
cider_vinegar = [faerie_apple, mineral_water]
lavender_oil = [lavender, lavender, lavender, lavender]
raw_oyster = [rothlyt_oyster, sun_lemon]


# CRAFTING tier 2

maple_clogs = maple_lumber
bronze_hatchet = bronze_ingot + maple_lumber
leather_calot = leather
maple_shortbow = maple_lumber + hempen_yarn
amateurs_file = bronze_ingot + bronze_ingot + leather
bronze_rings = bronze_ingot
bronze_rivets = bronze_ingot
undyed_hempen_cloth = hempen_yarn
hempen_halfgloves = undyed_hempen_cloth + hempen_yarn
hempen_underpants = undyed_hempen_cloth + hempen_yarn
hempen_pantalettes = undyed_hempen_cloth + hempen_yarn
leather_duckbills = leather + undyed_hempen_cloth
maple_sugar = maple_syrup
bronze_war_axe = bronze_ingot + bronze_ingot + maple_lumber
amateurs_pliers = bronze_ingot + bronze_rivets + fish_oil
bronze_plate = bronze_ingot + bronze_ingot
bronze_alembic = bronze_plate + bronze_rivets
leather_duckbills_of_gathering = leather + undyed_hempen_cloth
hempen_coif = undyed_hempen_cloth + hempen_yarn + leather
hempen_undershirt = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
hempen_camise = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
hempen_breeches_of_crafting = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + leather
maple_pattens = maple_lumber + undyed_hempen_cloth + leather
bronze_saw = bronze_ingot + bronze_rivets + maple_lumber
amateurs_awl = bronze_ingot + maple_lumber + fish_oil
bronze_skillet = bronze_plate + maple_lumber
copper_rings = copper_ingot
fingerless_leather_gloves = leather + leather + bronze_rivets
hempen_coif_of_gathering = undyed_hempen_cloth + hempen_yarn + leather
hempen_kurta = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
hempen_breeches = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + leather
amateurs_spinning_wheel = maple_lumber + maple_lumber + bronze_rivets + bronze_rivets
square_maple_shield = maple_lumber + bronze_rivets + bronze_rivets
amateurs_claw_hammer = bronze_ingot + maple_lumber + fish_oil
bronze_cross_pein_hammer = bronze_ingot + undyed_hempen_cloth + maple_lumber
bronze_doming_hammer = bronze_ingot + maple_lumber
bronze_hoplon = bronze_plate + bronze_plate + maple_lumber
copper_gorget = copper_ingot + copper_ingot + leather
copper_wristlets = copper_ingot + copper_rings + copper_rings
leather_culottes = leather + leather + undyed_hempen_cloth + undyed_hempen_cloth
hempen_bandana = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth
hempen_tunic = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + leather
hempen_cowl = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
hempen_chausses = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
hempen_tights = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
bronze_spear = maple_lumber + fish_oil + bronze_ingot
growth_formula_alpha = quicksilver + [shriekshroom, rock_salt]
maple_cane = maple_lumber + growth_formula_alpha
round_shield = maple_lumber + bronze_rivets, bronze_ingot
amateurs_mortar = bronze_ingot + bronze_ingot + maple_lumber
amateurs_culinary_knife = bronze_ingot + maple_lumber + ragstone_whetstone
bronze_labrys = bronze_ingot + bronze_ingot + maple_lumber
bronze_chaser_hammer = bronze_ingot + bronze_rivets + maple_lumber
bronze_knives = bronze_ingot + bronze_ingot + maple_lumber
bronze_head_knife = bronze_ingot + maple_lumber + ragstone_whetstone
bronze_pickaxe = bronze_ingot + undyed_hempen_cloth + maple_lumber
cloud_axe = bronze_war_axe + bronze_ingot
bronze_claw_hammer = bronze_ingot + maple_lumber + fish_oil
bronze_baselards = bronze_ingot + bronze_ingot + ash_lumber
amateurs_cross_pein_hammer = bronze_ingot + undyed_hempen_cloth + ash_lumber
bronze_file = bronze_ingot + bronze_ingot + hard_leather
bronze_pliers = bronze_ingot + bronze_rivets + clove_oil
amateurs_chaser_hammer = bronze_ingot + bronze_rivets + ash_lumber
bronze_mortar = bronze_ingot + bronze_ingot + ash_lumber
bronze_haubergeon = bronze_rings + bronze_rings + bronze_rings + undyed_hempen_cloth
bronze_sollerets = bronze_plate + bronze_rings + leather
bronze_chain_coif = bronze_plate + bronze_rings + leather
bronze_sallet = bronze_plate + bronze_ingot + bronze_rivets
amateurs_alembic = bronze_plate + bronze_rivets + copper_ingot
bronze_mitt_gauntlets = bronze_plate + bronze_rivets + leather
bronze_scutum = bronze_plate + bronze_plate + bronze_rivets + bronze_rivets + bronze_rivets
bronze_barbut = bronze_plate + bronze_rivets + copper_ingot
copper_earrings = copper_ingot + ragstone_whetstone
copper_ring = copper_ingot + ragstone_whetstone
copper_needle = copper_ingot + ragstone_whetstone
copper_choker = copper_ingot + copper_ingot + hard_leather
leather_ringbands = leather + bronze_ingot + hempen_yarn
leather_himantes = leather + leather + bronze_ingot + undyed_hempen_cloth
hard_leather_pot_helm = leather + hard_leather + bronze_rivets
leather_leggings = leather + leather + undyed_hempen_cloth
amateurs_thighboots = hard_leather + undyed_hempen_cloth + rubber
amateurs_duckbills = hard_leather + undyed_hempen_cloth
hempen_shepherds_tunic = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + copper_ingot
hempen_shortgloves = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
hempen_halfrobe = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + hempen_yarn
hempen_kecks = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + leather + copper_ingot
hempen_gaskins = undyed_hempen_cloth + hempen_yarn + leather + leather
amateurs_kurta = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn
amateurs_doublet_vest = undyed_hempen_cloth + hempen_yarn + leather + copper_ingot
hempen_bottoms = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + copper_ingot
amateurs_hempen_coif = undyed_hempen_cloth + hempen_yarn + hard_leather
amateurs_breeches = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + leather
maple_wand = growth_formula_alpha + [maple_branch]
whispering_maple_wand = maple_wand + growth_formula_alpha
ash_spinning_wheel = ash_lumber + ash_lumber + bronze_rivets + bronze_rivets
brass_spear = maple_lumber + fish_oil + bronze_ingot + brass_ingot
ash_mask = ash_lumber + leather + fish_oil
ash_pattens = ash_lumber + undyed_hempen_cloth + leather
square_ash_shield = ash_lumber + bronze_rivets + bronze_rivets
amateurs_doming_hammer = bronze_ingot + ash_lumber
amateurs_head_knife = bronze_ingot + ash_lumber + ragstone_whetstone
bronze_awl = bronze_ingot + ash_lumber + jellyfish_humours
amateurs_pickaxe = bronze_ingot + undyed_hempen_cloth + ash_lumber
bronze_scythe = bronze_ingot + ash_lumber + ragstone_whetstone
amateurs_saw = bronze_ingot + bronze_rivets + ash_lumber
bronze_ornamental_hammer = amateurs_chaser_hammer + bronze_rivets + bronze_rivets
bronze_culinary_knife = bronze_ingot + ash_lumber + ragstone_whetstone
bronze_sledgehammer = bronze_ingot + ash_lumber + animal_glue
amateurs_hatchet = bronze_ingot + ash_lumber
bronze_knuckles = bronze_ingot + bronze_ingot + hard_leather
spiked_bronze_labrys = bronze_ingot + bronze_ingot + bronze_ingot + ash_lumber
brass_daggers = brass_ingot + bronze_ingot + maple_lumber
brass_head_knife = bronze_head_knife + ragstone_whetstone + brass_ingot
undyed_cotton_cloth = cotton_yarn + cotton_yarn
iron_clapper = iron_ingot + undyed_cotton_cloth
birdsbeak_hammer = bronze_ingot + undyed_cotton_cloth + ash_lumber + jellyfish_humours
bronze_raising_hammer = bronze_ingot + bronze_plate + ash_lumber
amateurs_skillet = bronze_plate + ash_lumber
bronze_celata = bronze_plate + bronze_plate + bronze_rings
bronze_cuirass = bronze_plate + bronze_plate + bronze_rings
bronze_sabatons = bronze_plate + bronze_plate + bronze_rings + hard_leather
iron_plate = iron_ingot + iron_ingot
iron_rivets = iron_ingot
bronze_gauntlets = bronze_plate + bronze_plate + iron_rivets
iron_rings = iron_ingot
iron_joint_plate = iron_ingot
brass_alembic = amateurs_alembic + bronze_rivets + brass_ingot
iron_skillet = iron_plate + ash_lumber
bronze_buckler = bronze_plate + bronze_ingot + iron_rivets
copper_ear_cuffs = copper_ingot + copper_ingot + ragstone_whetstone
brass_spectacles = brass_ingot + clear_glass_lens
brass_rings = brass_ingot
brass_gorget = brass_ingot + brass_ingot + hard_leather
brass_wristlets = brass_ingot + brass_rings + brass_rings
amateurs_headgear = hard_leather + bronze_ingot + bronze_rivets
hard_leather_harness = hard_leather + leather + bronze_ingot
leather_targe = leather + leather + ash_lumber + bronze_rivets
hard_leather_armguards = hard_leather + hard_leather + bronze_ingot + bronze_rivets
hard_leather_himantes = hard_leather + hard_leather + iron_ingot + undyed_hempen_cloth
hard_leather_subligar = hard_leather + undyed_hempen_cloth + hempen_yarn
hard_leather_kecks = hard_leather + undyed_hempen_cloth + hempen_yarn
fingerless_hard_leather_gloves = hard_leather + hard_leather + iron_rivets
hempen_bracers = undyed_hempen_cloth + undyed_hempen_cloth + hard_leather + bronze_ingot
hempen_dress_gloves = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + hempen_yarn
hempen_doublet_vest_of_gathering = undyed_hempen_cloth + hempen_yarn + leather + copper_ingot
hempen_doublet_vest_of_crafting = undyed_hempen_cloth + hempen_yarn + leather + copper_ingot
hempen_robe = undyed_hempen_cloth + undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + hempen_yarn
cotton_turban = undyed_cotton_cloth + undyed_cotton_cloth + undyed_cotton_cloth
altered_cotton_bandana = undyed_cotton_cloth + undyed_cotton_cloth + undyed_cotton_cloth
cotton_shirt = undyed_cotton_cloth + cotton_yarn + hard_leather + hard_leather
cotton_cowl = undyed_cotton_cloth + undyed_cotton_cloth + undyed_hempen_cloth + undyed_hempen_cloth + cotton_yarn
cotton_chausses = undyed_cotton_cloth + undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn
cotton_tights = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn
cotton_scarf = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn
cotton_halfgloves = undyed_cotton_cloth + cotton_yarn
cotton_shepherds_slops = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + undyed_hempen_cloth
iron_spear = elm_lumber + iron_ingot + clove_oil
growth_formula_beta = quicksilver + [jellyfish_umbrella, rock_salt]
elm_cane = elm_lumber + growth_formula_beta
initiates_spinning_wheel = elm_lumber + elm_lumber + bronze_rivets + bronze_rivets
iron_lance = elm_lumber + iron_ingot + iron_ingot + hard_leather
ash_mask_lapis_lazuli = ash_lumber + lapis_lazuli + clove_oil + leather
iron_nails = iron_ingot
brass_bastard_sword = bronze_bastard_sword + brass_ingot + brass_ingot
brass_knuckles = bronze_knuckles + brass_ingot
brass_knives = brass_ingot + bronze_ingot + ash_lumber
chocobotail_saw = amateurs_saw + bronze_rivets + bronze_rivets
iron_war_axe = iron_ingot + iron_ingot + ash_lumber
iron_labrys = iron_ingot + iron_ingot + elm_lumber + hard_leather
iron_hatchet = iron_ingot + ash_lumber
iron_rivets = iron_ingot
iron_cross_pein_hammer = iron_ingot + undyed_cotton_cloth + elm_lumber
iron_doming_hammer = iron_ingot + elm_lumber
iron_chaser_hammer = iron_ingot + iron_rivets + elm_lumber
initiates_head_knife = iron_ingot + ash_lumber + mudstone_whetstone
iron_awl = iron_ingot + elm_lumber + clove_oil
initiates_sledgehammer = iron_ingot + elm_lumber + fish_glue
initiates_hatchet = iron_ingot + elm_lumber
brass_viking_sword = viking_sword + brass_ingot + aldgoat_leather
carnage_sword = brass_bastard_sword + aldgoat_leather
iron_daggers = iron_ingot + iron_ingot + elm_lumber
initiates_saw = iron_ingot + iron_rivets + ash_lumber
iron_claw_hammer = iron_ingot + elm_lumber + jellyfish_humours
iron_pickaxe = iron_ingot + undyed_cotton_cloth + ash_lumber
decorated_bronze_barbut = bronze_barbut + copper_ingot + brass_ingot
decorated_bronze_mitt_gauntlets = bronze_mitt_gauntlets + bronze_rivets + leather + brass_ingot
iron_hoplon = iron_plate + iron_plate + elm_lumber
initiates_alembic = iron_plate + bronze_rivets
initiates_skillet = iron_plate + elm_lumber
iron_sallet = iron_plate + iron_ingot + iron_rivets
iron_sabatons = iron_plate + iron_plate + bronze_rings + hard_leather
ironclad_bronze_buckler = bronze_buckler + bronze_ingot + iron_rivets
iron_celate = iron_plate + iron_plate + iron_rings
iron_cuirass = iron_plate + iron_plate + iron_rings
iron_gauntlets = iron_plate + iron_plate + iron_rings
brass_wristlets_of_crafting = brass_ingot + brass_rings + brass_rings
brass_earrings = brass_ingot + ragstone_whetstone
brass_circlet_sunstone = sunstone + brass_ingot + brass_ingot + brass_ingot
brass_circlet_danburite = danburite + brass_ingot + brass_ingot + brass_ingot
brass_circlet_fluorite = fluorite + brass_ingot + brass_ingot + brass_ingot
brass_circlet_sphene = sphene + brass_ingot + brass_ingot + brass_ingot
brass_circlet_malachite = malachite + brass_ingot + brass_ingot + brass_ingot
brass_circlet_lapis_lazuli = lapis_lazuli + brass_ingot + brass_ingot + brass_ingot
decorated_copper_scepter = copper_scepter + brass_ingot + ragstone_whetstone
brass_ring = brass_ingot + ragstone_whetstone
brass_ring_of_crafting = brass_ingot + ragstone_whetstone
hard_leather_ringbands = hard_leather + iron_ingot
hard_leather_skullcap = hard_leather + hard_leather + cotton_yarn
goatskin_pot_helm = aldgoat_leather + hard_leather + iron_rivets
goatskin_leggings = aldgoat_leather + aldgoat_leather + undyed_cotton_cloth
goatskin_ring = aldgoat_leather + cotton_yarn
hunting_hat = undyed_cotton_cloth + cotton_yarn + hard_leather
cotton_shepherds_tunic = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + brass_ingot
cotton_canvas = cotton_yarn + cotton_yarn + hempen_yarn + beeswax
cotton_kurta = undyed_cotton_cloth + undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn
cotton_coif = undyed_cotton_cloth + cotton_yarn + hard_leather
cotton_coif_of_gathering = undyed_cotton_cloth + cotton_yarn + hard_leather
cotton_breeches = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + leather
cotton_breeches_of_crafting = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + leather
initiates_doublet_vest = undyed_cotton_cloth + cotton_yarn + hard_leather + brass_ingot


# CRAFTING tier 3

bronze_bastard_sword = bronze_ingot + maple_lumber + [bone_chip]
leather_wristguards = leather + [animal_sinew]
bone_harpoon = maple_lumber + [bone_chip] + animal_glue
amateurs_grinding_wheel = maple_lumber + bronze_ingot + [ragstone]
leather_eyepatch = leather + [animal_sinew] + hempen_yarn
leather_shoes = leather + [animal_sinew] + rubber
hempen_dalmatica = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + [animal_sinew]
hempen_shepherds_slops = undyed_hempen_cloth + undyed_hempen_cloth + leather + [animal_sinew]
frumenty = raisins + honey + [sunset_wheat, aldgoat_milk, cinnamon]
bronze_daggers = bronze_ingot + bronze_ingot + maple_lumber + [bone_chip]
leather_crakows = leather + bronze_ingot + [animal_sinew] + rubber
altered_thightboots = leather + bronze_ingot + [animal_sinew] + rubber
leather_choker = leather + [animal_sinew]
hempen_dalmatica_of_gathering = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + [animal_sinew]
hempen_sarouel = undyed_hempen_cloth + hempen_yarn + leather + [animal_sinew]
leather_grimoire = enchanted_copper_ink + leather + hempen_yarn + [maple_log]
crayfish_ball = rye_flour + [crayfish, crayfish, crayfish]
battered_fish = olive_oil + table_salt + [haddock, popoto]
rolanberry_shaved_ice = maple_syrup + [mineral_water, rolanberry, buffalo_milk]
flatbread = rye_flour + table_salt + [mineral_water]
grilled_trout = table_salt + [princess_trout]
maple_longbow = maple_lumber + hempen_yarn + [maple_branch]
maple_crook = maple_lumber + [beastkin_blood]
maple_fishing_rod = maple_lumber + bronze_ingot + [maple_branch]
plumed_maple_shortbow = maple_shortbow + [maple_branch, cock_feather]
ash_macuahuitl = ash_lumber + [obsidian]
ramhorn_harpoon = ash_lumber + [ram_horn]
viking_sword = bronze_ingot + leather + [bone_chip]
bone_ring = ragstone_whetstone + [bone_chip]
bone_necklace = copper_rings + [soiled_femur, soiled_femur]
copper_scepter = copper_ingot + [marbled_eye]
leather_mitts = leather + leather + [animal_sinew]
leather_lightmitts = leather + leather + [animal_sinew]
leather_boots = leather + undyed_hempen_cloth + rubber + [animal_sinew]
leather_wristbands = leather + animal_glue + [bone_chip, bone_chip]
leather_sandals = leather + maple_lumber + [animal_sinew]
altered_leather_thighboots = leather + maple_lumber + [animal_sinew]
amateurs_smithing_gloves = hard_leather + hard_leather + [animal_sinew]
leather_jacket = hard_leather + hard_leather + hard_leather + [animal_sinew]
hard_leather_wristguards = hard_leather + [beast_sinew]
hempen_hat = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + [cock_feather]
hempen_tabard = undyed_hempen_cloth + hempen_yarn + leather + [animal_sinew]
hempen_work_gloves = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + [moko_grass]
hempen_acton = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + [moko_grass]
amateurs_slops = undyed_hempen_cloth + undyed_hempen_cloth + leather + [animal_sinew]
amateurs_dalmatica = undyed_hempen_cloth + undyed_hempen_cloth + hempen_yarn + [cock_feather]
hempen_trousers = undyed_hempen_cloth + hempen_yarn + leather + bronze_rivets + [animal_sinew]
maple_picatrix = enchanted_copper_ink + maple_lumber + hempen_yarn + [maple_log]
engraved_leather_grimoire = leather_grimoire + leather + leather + [ash_log]
tree_toad_legs = smooth_butter + sunset_wheat_flour + [tree_toad, allagan_snail, garlean_garlic]
chanterelle_saute = smooth_butter + [chanterelle]
braised_pipira = smooth_butter + table_salt + [pipira, chanterelle]
boiled_crayfish = table_salt + [crimson_crayfish, mineral_water]
mutton_stew = sunset_wheat_flour + [mutton_loin, wild_onion, coerthan_carrot, mineral_water]
goby_ball = rye_flour + [dusk_goby, dusk_goby, dusk_goby]
jack_o_lantern = beeswax + maple_syrup + [ogre_pumpkin, mineral_water]
ragstone_grinding_wheel = ash_lumber + bronze_ingot + [ragstone]
amateurs_fishing_rod = ash_lumber + bronze_ingot + [ash_branch]
feathered_harpoon = ash_lumber + animal_glue + [crow_feather, soiled_femur]
wrapped_maple_longbow = maple_longbow + hard_leather + [ash_branch, ash_branch]
ash_shortbow = ash_lumber + hempen_yarn + [ash_branch]
bronze_spatha = bronze_ingot + hard_leather + [ram_horn]
bronze_scepter = bronze_ingot + [marbled_eye]
decorated_bone_staff = bone_staff + [soiled_femur, bat_fang, bat_fang]
brass_cudgel = bronze_ingot + brass_ingot + [marbled_eye]
fang_earrings = brass_ingot + hard_leather + [bat_fang]
hard_leather_shoes = hard_leather + rubber + [beast_sinew]
leather_jackboots = hard_leather + undyed_hempen_cloth + rubber + [beast_sinew]
hard_leather_sandals = hard_leather + ash_lumber + [beast_sinew]
hard_leather_eyepatch = hard_leather + hempen_yarn + [beast_sinew]
hard_leather_lightmitts = hard_leather + hard_leather + [beast_sinew]
hard_leather_caligae = hard_leather + bronze_rivets + [beast_sinew]
hard_leather_thighboots = hard_leather + bronze_rivets + [beast_sinew]
hard_leather_crakows = hard_leather + bronze_ingot + rubber + [beast_sinew]
hard_leather_boots = hard_leather + undyed_hempen_cloth + rubber + [beast_sinew]
hard_leather_choker = hard_leather + [beast_sinew]
stablehands_hat = undyed_cotton_cloth + [straw, straw, straw]
striped_cotton_slops = undyed_cotton_cloth + undyed_cotton_cloth + hard_leather + [animal_sinew]
cotton_sarouel = undyed_cotton_cloth + cotton_yarn + hard_leather + [beast_sinew]
budding_maple_wand = maple_wand + growth_formula_alpha + [beastkin_blood]
potion = distilled_water + [tinolqa_mistletoe, chanterelle]
ash_picatrix = enchanted_copper_ink + ash_lumber + cotton_yarn + [ash_log]
ether = distilled_water + [tinolqa_mistletoe, imp_wing]
grilled_dodo = table_salt + [dodo_tenderloin, garlean_garlic]
bubble_chocolate = kukuru_powder + kukuru_butter + maple_sugar + [buffalo_milk]
pearl_chocolate = kukuru_butter + maple_sugar + [aldgoat_milk]
mole_loaf = flatbread + tomato_sauce + [black_pepper, chicken_egg, wild_onion, mole_meat]
parsnip_salad = olive_oil + [alpine_parsnip, la_noscean_lettuce, cieldalaes_spinach, buffalo_beans, mineral_water]
pie_dough = sunset_wheat_flour + table_salt + [mineral_water]
rabbit_pie = pie_dough + [coerthan_carrot, marmot_meat, wild_onion, black_pepper]
salt_cod = table_salt + [tiger_cod]
grilled_carp = table_salt + [maiden_carp]
elm_fishing_rod = elm_lumber + iron_ingot + [ash_branch]
elm_longbow = elm_lumber + cotton_yarn + [ash_branch, ash_branch]
elm_crook = elm_lumber + [beastkin_blood]
initiates_fishing_rod = elm_lumber + iron_ingot + [yew_branch]
plumed_bronze_pickaxe = bronze_pickaxe + hard_leather + [crow_feather]
bat_fang_needle = ragstone_whetstone + [bat_fang]
toothed_ramhorn_staff = ramhorn_staff + ragstone_whetstone + [ram_horn]
fang_necklace = cotton_yarn + [bat_fang, bat_fang]
crow_fly = brass_ingot + [crow_feather]
hard_leather_espadrilles = hard_leather + elm_lumber + [beast_sinew]
hard_leather_wristbands = hard_leather + fish_glue + [white_coral, white_coral]
hard_leather_wristbands_of_gathering = hard_leather + fish_glue + [white_coral, white_coral]
goatskin_cesti = aldgoat_leather + bronze_ingot + [beast_sinew]
goatskin_mitts = aldgoat_leather + aldgoat_leather + [beast_sinew]
goatskin_wristguards = aldgoat_leather + [beast_sinew]
initiates_gloves = aldgoat_leather + aldgoat_leather + [beast_sinew]
cotton_tabard = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + hard_leather + [animal_sinew]
padded_hempen_trousers = undyed_hempen_cloth + cotton_yarn + hard_leather + [beast_sinew]
cotton_dalmatica = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + [beast_sinew]
cotton_dalmatica_of_gathering = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + [beast_sinew]
altered_cotton_dalmatica = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + [beast_sinew]
cotton_trousers = undyed_cotton_cloth + cotton_yarn + leather + bronze_rivets + [animal_sinew]
cotton_acton = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + [dodo_feather]
cotton_work_gloves = undyed_cotton_cloth + undyed_hempen_cloth + cotton_yarn + [cotton_boll]
padded_cotton_trousers = undyed_cotton_cloth + cotton_yarn + hard_leather + iron_rivets + [animal_skin]
initiates_slops = undyed_cotton_cloth + undyed_cotton_cloth + cotton_yarn + [beast_sinew]
hard_leather_grimoire = enchanted_iron_ink + hard_leather + cotton_yarn + [elm_log]
ash_wand = growth_formula_beta + [ash_branch]
mortar = distilled_water + [limestone, limestone, fine_sand]
engraved_hard_leather_grimoire = hard_leather_grimoire + hard_leather + hard_leather + [yew_log]
dodo_omelette = smooth_butter + table_salt + tomato_sauce + [highland_parsley, aldgoat_milk, dodo_egg]
meat_miqabob = table_salt + [dodo_tenderloin, paprika, ruby_tomato]
cottage_cheese = cider_vinegar + [aldgoat_milk]
lentils_and_chestnuts = olive_oil + [gridanian_chestnut, lalafellin_lentil, galago_mint, black_pepper, sour_red]
roasted_nopales = table_salt + [nopales, blue_cheese]
stone_soup = table_salt + [ragstone, mineral_water, coerthan_carrot, popoto]
apple_tart = pie_dough + maple_sugar + smooth_butter + [faerie_apple, chicken_egg, cinnamon]
walnut_bread = sunset_wheat_flour + table_salt + smooth_butter + [buffalo_milk, gridanian_walnut]
crab_ball = rye_flour + [helmet_crab, helmet_crab, helmet_crab]
chicken_and_mushrooms = smooth_butter + table_salt + [gil_bun, chicken_breast]
antelope_stew = sunset_wheat_flour + [antelope_shank, wild_onion, coerthan_carrot, popoto]
grilled_warmwater_trout = table_salt + [warmwater_trout, garlean_garlic]


def ffxivcraftingaide(crafting_item):
    raws_list = {}
    cart = []
    while True:
        if crafting_item == "quit":
            for x in cart:
                raws_list1 = {x: cart.count(x)}
                raws_list.update(raws_list1)
            for x in raws_list:
                print(f"{raws_list.get(x)!r} x {x!r}")
            break
        elif True:
            for item in crafting_item:
                cart += item
#        else:
#           print("Sorry, I don't understand that. Try to avoid using an apostrophe.")
